@startuml

/'Adicionei Cliente <-> Resultado'/

/' ABAIXO COLOCAR AS LINHAS RETAS <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
skinparam linetype ortho'/

skinparam classAttributeIconSize 0
hide empty methods
hide empty attributes
left to right direction
/'top to bottom direction'/

class Employee {
- employeeID
/'- organizationRole'/
- name
- address
- phoneNumber
- e-Mail
- standardOccupationalClassificationCode
}

class Test{
- code
- NhsCode
- createdAt
- **testType**
- **designation**

}

class Sample{
- barCode

}

class FinalResult{}
class ChemicalResult{}
/'class ClinicalResult{}'/
/' TIREI ISTO: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
class Diagnosis{}'/
class Parameter{
- designation
}
class Notification{
- textDescription
}
/'class Courier{}'/
/' MUDEI ISTO: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'/
class SpecialistDoctorResult{
- **report**
- **diagnosis**
}
class PandemicReport{}
class PandemicForecast{
- **totalPandemicNextDay**
- **totalPandemicNextWeek**
- **totalPandemicNextMonth**
}

class PandemicVerifiedInfo{
- **numPandemicTests**
- **positivePandemic**
- **totalPandemicDay**
- **totalPandemicWeek**
- **totalPandemicMonth**
- **totalPandemicYear**
}

class Client{
- name
- citizenCardNum
- nhsNum
- birthDate
- sex
- taxIdNum
- phoneNum
- email
}
class Administrator{}

/'class Doctor{}'/
class Receptionist{}

class MedicalLabTechnician{}

class ClinicalChemistryTechnologist{}

class SpecialistDoctor{
- doctorIndexNumber
}

class LaboratoryCoordinator{}

class ClinicalAnalysisLaboratory{
- laboratoryID
- name
- address
- phoneNumber
- numTIN
}

class ChemicalLaboratory{
- name
- address
- phoneNumber
- numTIN
}

class Application{}
class ChemicalAnalysis{}
/'class ClinicalAnalysis{}'/
/' TIREI ISTO: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
class TestType{
- designation
}'/
class Category{
- code
- description
- nhsId
}
/' TIREI ISTO: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
class Covid19Test{
}
class BloodTest{

}

class OtherTest{
}'/

class Company{
- designation
}

/'class NHS{}'/
class nhsAPI{}
/'class ExternalModule{}'/

class LabOrder{}



/'LAYOUT PURPOSES'/
together {
class ChemicalLaboratory
class ClinicalAnalysisLaboratory
class ChemicalAnalysis
class Test


}

Company -[hidden]--> ChemicalLaboratory

/'Company -[hidden]--> ClinicalAnalysisLaboratory'/

ChemicalLaboratory -[hidden]down-|> ClinicalAnalysisLaboratory
MedicalLabTechnician -[hidden]up-|> ClinicalAnalysisLaboratory
ClinicalAnalysisLaboratory -[hidden]-|> Receptionist
ClinicalChemistryTechnologist -[hidden]up-|> ChemicalLaboratory
ClinicalAnalysisLaboratory -[hidden]up-|> Receptionist

PandemicReport -[hidden]down-|> Application

/' ACRESCENTEI AQUI AO RETIRAR TEST REQUESTED BY CLIENT '/
PandemicReport -[hidden]up-|> Company

/'ACRESCENTEI ISTO PARA O NHSAPI FICAR EM BAIXO DO Covid19Data'/
nhsAPI -[hidden]down-|> PandemicReport


/'Company -[hidden]left-|> Company'/





together {
class Client
class Test
}


/' TIREI ISTO: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
together {
class Covid19Test
class BloodTest
class OtherTest
}

TestType -[hidden]--> BloodTest
TestType -[hidden]--> Covid19Test
TestType -[hidden]--> OtherTest'/

together {
/' TIREI ISTO: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
class Diagnosis'/
/' MUDEI ISTO: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'/
class SpecialistDoctorResult
}

LabOrder -[hidden]--> Client









/' END OF LAYOUT PURPOSES '/


Employee "1..*" -- "1" Company : works for >
Receptionist "1" -- "1" Employee : is of >
MedicalLabTechnician "1" -- "1" Employee : is of >
ClinicalChemistryTechnologist "1" -- "1" Employee : is of >
SpecialistDoctor "1" -- "1" Employee : is of >
LaboratoryCoordinator "1" -- "1" Employee : is of >
Administrator "1" -- "1" Employee : is of >

Company "1" -- "*" Test : performs >
/' TIREI ISTO: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Company "1" -- "*" TestType : conducts >'/
Company "1" - "1" ChemicalLaboratory : owns >
/' MUDEI O ABAIXO: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'/
Company "1" -- "1..*" ClinicalAnalysisLaboratory : owns >
Company "1" -- "1..*" PandemicReport : reports >
Parameter "*" -- "1" Category : presented under >
/'ACRESCENTEI LINHA ABAIXO'/
Parameter "*" -- "1" Administrator : created by >
Category "*" -- "1" Administrator : created by >
/'RETIREI A LINHA ABAIXO TEST IS REQUESTED BY CLIENT'/
/'Test "*" -- "1" Client : requested by >'/
/'Test -- Application : is known by >'/
/' TIREI ISTO: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Test "*" -- "1" TestType : is of >'/
/' MUDEI O ABAIXO: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'/
Test "1" -- "1" Sample : collects >
/' TIREI ISTO: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Test "*" -- "1..*" Parameter : requested analysis of >'/
Test "*" -- "1..*" MedicalLabTechnician : registered by >
Test "1" - "1" LabOrder : requested by >
LabOrder "1..*" -- "1" Client : owns <
Receptionist "1" -- "*" Client : registers >
Receptionist "1" -- "*" Test : registers >
/'PERGUNTAR CLIENTE LINHA ABAIXO'/
Receptionist "1..*" -- "1" ClinicalAnalysisLaboratory : works for >
/'MedicalLabTechnician "1" -- "*" Sample : collects >'/
MedicalLabTechnician "1..*" -- "1" ClinicalAnalysisLaboratory : works for >
MedicalLabTechnician "1" -- "*" Sample : records >
/'Sample -- Application : is known >'/
/'Sample "*" -- "1" ChemicalLaboratory : sent to >'/
ClinicalChemistryTechnologist "1..*" -- "1" ChemicalLaboratory : works for >
/'ClinicalChemistryTechnologist "1" -- "*" Sample : receives >'/
ClinicalChemistryTechnologist "1" -- "*" ChemicalAnalysis : performs >
ClinicalChemistryTechnologist "1" -- "*" ChemicalResult : records >
/'LabOrder -- Doctor : prescribed by >'/
ChemicalResult "*" -- "1" SpecialistDoctor : analysed by >
/' TIREI ISTO: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
SpecialistDoctor "1" -- "*" Diagnosis : makes >'/
/' MUDEI ISTO: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'/
SpecialistDoctor "1" -- "*" SpecialistDoctorResult : makes >
/'SpecialistDoctorReport -- Client : delivered to >'/
/'SpecialistDoctorReport -- Application : known by >'/
/' MUDEI ISTO: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'/
SpecialistDoctorResult "*" -- "1" LaboratoryCoordinator : validated by >
/'ClinicalResult -- Application : known by >'/
/'ClinicalResult -- LaboratoryCoordinator : validated by >'/
/' TIREI ISTO: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Diagnosis "*" -- "1" LaboratoryCoordinator : validated by >'/
LaboratoryCoordinator "1" -- "*" FinalResult : confirms >
Client "1" -- "1..*" Notification : receives >
FinalResult "1..*" -- "1" Client : known by >
/'Result -- MedicalLabTechnician : known by >'/
/'Result -- ClinicalChemistryTechnologist : known by >'/
/'Result -- SpecialistDoctor : known by >'/
/'Result -- LaboratoryCoordinator : known by >'/
nhsAPI "1" -- "1..*" PandemicReport : receives >
Application "1" --- "1..*" PandemicReport : generates >
PandemicVerifiedInfo "1" -- "1" PandemicReport : part of >
PandemicForecast "1" -- "1" PandemicReport : part of >
/' TIREI ISTO: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Covid19Test "*" -- "1" TestType : part of >'/
/' ABAIXO MUDEI DE COVID119TEST PARA TEST: <<<<<<<<<<<<<<<<<<<<<<<<<<<<'/
Test "*" -- "1..*" Parameter : characterized by >
/' TIREI ISTO: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
BloodTest "*" -- "1" TestType : part of >
BloodTest "*" -- "3..*" Parameter : characterized by >'/
/' ABAIXO MUDEI DE OTHERTEST PARA TEST: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'/
Application "1" - "*" Test : supports >
Application "1" - "*" Notification : sends >
Application "1" -- "1" Company : knows <
/' TIREI ISTO: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
OtherTest "*" -- "1" TestType : part of >
OtherTest "*" -- "1..*" Parameter : characterized by >'/
















@enduml