@startuml

/'Adicionei Cliente <-> Resultado'/

skinparam classAttributeIconSize 0

class Test{
- **code**
- **NhsCode**
- **createdAt**
VER MELHOR
}
class Sample{
- Client CLASS
- barCode
}
class Result{}
class ChemicalResult{}
class ClinicalResult{}
class Diagnosis{}
class Parameter{}
class Notification{}
class Courier{}
class SpecialistDoctorReport{}
class Covid19Data{}
class Forecast{
- totalCovidNextDay
- totalCovidNextWeek
- totalCovidNextMonth
}
class NHSDailyReports{
- numCovidTests
- positiveCovid
- totalCovidDay
- totalCovidWeek
- totalCovidMonth
- totalCovidYear
}
class Client{
- **name**
- citizenCardNum
- nhsNum
- birthDate
- sex
- taxIdNum
- phoneNum
- email
}
class Administrator{}
class Doctor{}
class Receptionist{}
class MedicalLabTechnician{}
class ClinicalChemistryTechnologist{}
class SpecialistDoctor{}
class LaboratoryCoordinator{}
class ClinicalAnalysisLaboratory{}
class ChemicalLaboratory{}
class Application{}
class ChemicalAnalysis{}
class ClinicalAnalysis{}
class TestType{
- **designation**
}
class Category{
- **code**
- **description**
- **nhsId**
}
class Covid19Test{
}
class BloodTest{
}
class OtherTest{
}
class Company{
- **designation**
}
class NHS{}
class NHSAPI{}
class ExternalModule{}
class LabOrder{
- TestType CLASS
- Parameter CLASS
}
/'LAYOUT PURPOSES'/
together {
class ChemicalLaboratory
class ClinicalAnalysisLaboratory
class ChemicalAnalysis
class Test
}

Company -[hidden]--> ChemicalLaboratory
Company -[hidden]--> ClinicalAnalysisLaboratory
ChemicalLaboratory -[hidden]--> ClinicalAnalysisLaboratory
MedicalLabTechnician -[hidden]up-|> ClinicalAnalysisLaboratory
/'Acrescentei a linha abaixo'/
Receptionist -[hidden]up-|> ClinicalAnalysisLaboratory
ClinicalChemistryTechnologist -[hidden]> ChemicalLaboratory
ClinicalChemistryTechnologist -[hidden]up-|> ChemicalLaboratory

Covid19Data -[hidden]down-|> Application




together {
class Client
class Test
}



together {
class Covid19Test
class BloodTest
class OtherTest
}

TestType -[hidden]--> BloodTest
TestType -[hidden]--> Covid19Test
TestType -[hidden]--> OtherTest





/' END OF LAYOUT PURPOSES '/


Company "1" -- "*" Test : performs >
Company "1" -- "*" TestType : conducts >
Company "1" -- "1" ChemicalLaboratory : owns >
Company "1" -- "*" ClinicalAnalysisLaboratory : owns >
Company -- Covid19Data : reports >
Parameter "*" -- "1" Category : presented under >
Category "*" -- "1" Administrator : created by >
Test "*" -- "1" Client : requested by >
/'Test -- Application : is known by >'/
Test "*" -- "1" TestType : is of >
Test "1" -- "*" Sample : collects >
Test "*" -- "1..*" Parameter : requested analysis of >
Test -- MedicalLabTechnician : registered by >
Receptionist -- Client : registers >
Receptionist -- Test : registers >
Receptionist - ClinicalAnalysisLaboratory : belongs to >
MedicalLabTechnician -- Sample : collects >
MedicalLabTechnician -- ClinicalAnalysisLaboratory : belongs to >
MedicalLabTechnician -- Sample : records >
/'Sample -- Application : is known >'/
Sample -- ChemicalLaboratory : sent to >
ClinicalChemistryTechnologist -- ChemicalLaboratory : belongs to >
ClinicalChemistryTechnologist -- Sample : receives >
ClinicalChemistryTechnologist -- ChemicalAnalysis : performs >
ClinicalChemistryTechnologist -- ChemicalResult : records >
/'LabOrder -- Doctor : prescribed by >'/
ChemicalResult -- SpecialistDoctor : analysed by >
SpecialistDoctor - Diagnosis : makes >
SpecialistDoctor -- SpecialistDoctorReport : writes >
/'SpecialistDoctorReport -- Client : delivered to >'/
/'SpecialistDoctorReport -- Application : known by >'/
SpecialistDoctorReport -- LaboratoryCoordinator : validated by >
/'ClinicalResult -- Application : known by >'/
ClinicalResult -- LaboratoryCoordinator : validated by >
Client -- Notification : receives >
Result -- Client : known by >
/'Result -- MedicalLabTechnician : known by >'/
/'Result -- ClinicalChemistryTechnologist : known by >'/
/'Result -- SpecialistDoctor : known by >'/
/'Result -- LaboratoryCoordinator : known by >'/
NHS -- Covid19Data : receives >
Application -- Covid19Data : generates >
NHSDailyReports -- Covid19Data : part of >
Forecast -- Covid19Data : part of >
Covid19Test -- TestType : part of >
Covid19Test -- Parameter : characterized by >
BloodTest -- TestType : part of >
BloodTest -- Parameter : characterized by >
Application -- OtherTest : supports >
OtherTest -- TestType : part of >
OtherTest -- Parameter : characterized by >
















@enduml