@startuml

left to right direction
skinparam packageStyle rectangle
actor Receptionist
actor "Medical Lab Technician" as MLT
actor Administrator
actor "Clinical Chemistry Technologist" as CCT
actor "Laboratory Coordinator" as LC
actor "Specialist Doctor" as SD
actor Client
actor Application



rectangle System {
Receptionist --> (UC 1 - Register a new client)
Receptionist --> (UC 2 - Register a test to be performed to a registered client)
MLT --> (UC 3 - Register all the clinical blood and Covid-19 tests performed)
MLT --> (UC 4 - Record the samples collected in the scope of a given test)
CCT --> (UC 8 - Record the chemical analysis results)
Administrator --> (UC 5 - Specify a new type of test and its collecting methods)
Administrator --> (UC 6 - Specify a new test parameter and categorize it)
Administrator --> (UC 7 - Specify a new parameter category)
SD --> (UC 11 - Make a diagnosis in the system)
SD --> (UC 12 - Register a report in the system)
LC --> (UC 9 - Validate the chemical test/result and associated diagnosis)
LC --> (UC 10 - Post the chemical test/result and associated diagnosis in the central application)
Application --> (UC 13 - Generate Covid-19 reports)
}


@enduml