package app.domain.model;

/**
 * Represents a MyBarcode through:
 * the barcode generated by the API and the barcode number.
 *
 * This class exists in order to allow every Adapter class to return the same type of object.
 * (Adapter Pattern)
 *
 * @author Ana Albergaria
 */

public class MyBarcode {

    /**
     * The barcode of the MyBarcode.
     */
    private Object barcode;

    /**
     * The barcode number of the MyBarcode.
     */
    private String barcodeNumber;

    /**
     * The total number of existing barcodes.
     */
    private static int totalBarcodes = 1;

    /**
     * Builds a Sample's instance receiving:
     * the barcode
     * the barcodeNumber
     *
     * @param barcode the barcode of the MyBarcode
     * @param barcodeNumber the barcode number of the MyBarcode
     */
    public MyBarcode(Object barcode, String barcodeNumber) {
        this.barcode = barcode;
        this.barcodeNumber = barcodeNumber;
        totalBarcodes++;
    }

    /**
     * Returns the barcode (generated by the API) of the MyBarcode.
     *
     * @return barcode of the MyBarcode
     */
    public Object getBarcode() {
        return barcode;
    }

    /**
     * Returns the barcode number of the MyBarcode.
     *
     * @return barcode number of the MyBarcode
     */
    public String getBarcodeNumber() {
        return barcodeNumber;
    }

    /**
     * Returns the total number of the barcodes.
     *
     * @return total number of the barcodes
     */
    public static int getTotalBarcodes() {
        return totalBarcodes;
    }
}

