@startuml
hide empty methods
hide empty attributes
left to right direction
skinparam classAttributeIconSize 0

class ParameterCategoryDto {
    -code
    -name
    +ParameterCategory(code, name)
    +getCode()
}

class ParameterCategoryMapper {
    +List<ParameterCategoryDto> toDto(List<ParameterCategory> parameterCategories)
    +ParameterCategoryDto toDTO(ParameterCategory pc)
}

class ParameterCategoryStore {
    +getCategoryByCode(code)
}

class ParameterStore {
    +createParameter(parameterCode, shortName, description, pc)
    +validateParameter(parameter)
    +saveParameter(parameter)
}

class Parameter {
  -parameterCode: String
  -shortName: String
  -description: String
  -pc: ParameterCategory
  +Parameter(parameterCode, shortName, description, pc)
}

class ParameterCategory {
   -code: String
   -name: String
}

class Company {
  -designation: String
  +getParameterStore()
  +getParameterCategoryStore()
}

class CreateParameterController {
  +createParameter(parameterCode, shortName, description, pcCode)
  +saveParameter()
}

class CreateParameterUI {

}

CreateParameterUI ..> CreateParameterController
CreateParameterController ..> Company
CreateParameterController ..> ParameterCategoryStore
CreateParameterController ..> ParameterStore
CreateParameterController ..> ParameterCategoryMapper
ParameterCategoryMapper ..> ParameterCategory
ParameterCategoryMapper ..> ParameterCategoryDto
CreateParameterUI ..> ParameterCategoryDto
ParameterCategoryStore -- ParameterCategory : adopts >
Company "1" -- "1" ParameterCategoryStore : uses >
Company "1" -- "1" ParameterStore : uses >
ParameterStore "1" -- "*" Parameter : capable of analysing >
Parameter "*" -- "1" ParameterCategory : presented under >


@enduml