@startuml
hide empty methods
hide empty attributes
left to right direction
skinparam classAttributeIconSize 0

class ParameterCategoryStore {
    +getCategoryByCode(code)
}

class Parameter {
  -String parameterCode
  -String shortName
  -String description
  -ParameterCategory pc
  +Parameter(parameterCode, shortName, description, pc)
  +createParameter(parameterCode, shortName, description, pc)
  +validateParameter(parameter)
  +saveParameter(parameter)
}

class ParameterCategory {
   -String code
   -String name
   +ParameterCategory(code, name)
   +getCode()
}

class Company {
  -String designation
  +getParameterStore()
  +getParameterCategoryStore()
}

class CreateParameterController {
  +createParameter(parameterCode, shortName, description, pcCode)
  +saveParameter()
}

class CreateParameterUI {

}

CreateParameterUI ..> CreateParameterController
CreateParameterController ..> Company
CreateParameterController ..> ParameterCategoryStore
CreateParameterController ..> Parameter
ParameterCategoryStore ..> ParameterCategory
Company "1" -- "1" ParameterCategoryStore : uses >
Company "1" -- "*" ParameterCategory : adopts >
Parameter "1..*" -- "1" ParameterCategory : presented under >


@enduml