@startuml
autonumber
'hide footbox
actor "Administrator" as ADM

participant ":CreateParameterUI" as UI
participant ":CreateParameterController" as CTRL
participant "cmp\n:Company" as CMP
participant "store\n:ParameterCategoryStore" as STORE
participant ":CreateParameterCategoryController" as PCCTRL
participant "prm\n:Parameter" as PRM
participant "pc\n:ParameterCategory" as PC
participant "lc\n:List<ParameterCategory>" as LIST_CAT

activate ADM
ADM -> UI : asks to create a new parameter
activate UI
UI --> ADM : requests data(i.e., parameterCode, shortName, description)
deactivate UI

ADM -> UI : types requested data
activate UI

UI -> CTRL : lc = getParameterCategories()
activate CTRL

CTRL -> CMP : categoriesStore = getParameterCategoryStore()
activate CMP
|||
deactivate CMP
CTRL -> STORE : categoriesList = getParameterCategoriesStore()
activate STORE
|||
deactivate STORE
deactivate CTRL

UI --> ADM : shows parameter categories list and asks to select one
deactivate CMP
deactivate UI

ADM -> UI : selects a parameter category
activate UI

loop while administrator wants to create one more parameter
UI -> CTRL : createParameter(parameterCode, shortName, description, pcCode)
activate CTRL

CTRL -> PCCTRL : pc = getCategoryByCode(pcCode)
activate PCCTRL
|||
deactivate PCCTRL

CTRL -> CMP: prm = createParameter(parameterCode, shortName, description, pc)
activate CMP

CMP --> PRM**: create(parameterCode, shortName, description, pc)
CTRL -> CMP: validateParameter(prm)
end


CTRL --> UI: result

UI --> ADM: shows all data and requests confirmation
deactivate CMP
deactivate CTRL
deactivate UI

ADM -> UI : confirms the data
activate UI
UI -> CTRL : saveParameter()
activate CTRL

CTRL -> CMP : saveParameter(parameter)
activate CMP

CMP -> CMP: validateParameter(parameter)
CMP -> CMP: addParameter(parameter)

CTRL --> UI: result

UI --> ADM : informs operation success
deactivate CMP
deactivate CTRL
deactivate UI

deactivate ADM

@enduml