@startuml
hide empty methods
hide empty attributes
left to right direction
skinparam classAttributeIconSize 0

class Company {
  -String designation
  +createParameterCategory(code, name, nhsId)
  +validateParameterCategory(pc)
  +saveParameterCategory(pc)
  +addParameterCategory(pc)
}

class ParameterCategory {
   -String code
   -String name
   -String nhsId
   +ParameterCategory(code, name, nhsId)
   +getCode(code)
}

class CreateParameterCategoryController {
  +createParameterCategory(code, name, nhsId)
  +saveParameterCategory()
}

class CreateParameterCategoryUI {
}

CreateParameterCategoryUI ..> CreateParameterCategoryController
CreateParameterCategoryController ..> Company
CreateParameterCategoryController ..> ParameterCategory
Company "1" --> "*" ParameterCategory : adopts


@enduml