@startuml
autonumber
'hide footbox
actor "Laboratory coordinator" as ADM
participant ":ImportTestUI  " as UI
participant "testFile:TestFileUtils" as TST
participant ":ImportTestController" as CTRL
participant ":Company" as PLAT
participant ":RegisterClientController" as CLIENT_CTRL
participant ":CreateFileTestController" as ORG

activate ADM
ADM -> UI : asks to import clinical tests from a CSV file.
activate UI

UI -> CTRL : create()
activate CTRL
CTRL -> CLIENT_CTRL** : createClientCtrl = create()
CTRL -> ORG** : createClientCtrl = create()
deactivate CTRL




UI --> ADM : shows the file chooser and asks to select the file.
deactivate UI

ADM -> UI : selects requested data
activate UI

UI -> TST** : Create()
UI -> TST : List<TestFileDTO>testFileDTO = getTestDataToDto(pathOfFile)
activate TST
deactivate TST
loop for each TestFileDTO of the list

UI -> CTRL : createTestsFromFile(TestFileDTO)
activate CTRL

/'
CTRL -> TEST_LIST** : create()
'/


CTRL -> CLIENT_CTRL : existsClient = createClient(testFileDTO.getClientDTO())
activate CLIENT_CTRL
deactivate CLIENT_CTRL

alt client doesn't exist in Client Store
CTRL -> CLIENT_CTRL : clientCreation = saveClient()
activate CLIENT_CTRL
deactivate CLIENT_CTRL
end
CTRL -> ORG : createTest(TestFileDTO)
activate ORG
deactivate ORG

CTRL -> ORG : saveTest()
activate ORG
deactivate ORG

CTRL --> UI: result
deactivate CTRL
end

UI --> ADM : informs operation success\n and shows all created tests
deactivate ORG
deactivate CTRL
deactivate UI

deactivate ADM

@enduml
