@startuml

autonumber
actor "Lab Coordinator" as MLT

activate MLT
MLT -> ":System" :  asks to import clinical tests from a CSV file.
activate ":System"
":System" --> MLT : shows the file chooser and asks to select the file.
deactivate ":System"

MLT -> ":System" : selects requested data
activate ":System"
":System" --> MLT : shows the number of clinical tests to be imported\n and requests confirmation
deactivate ":System"
MLT -> ":System" : confirms the data
activate ":System"
":System" --> MLT : informs operation success
deactivate ":System"

@enduml