@startuml
autonumber
actor Administrator as A

activate A
A -> ":System" : starts registering a new employee
activate ":System"
":System" --> A : asks to select the employee role
deactivate ":System"

A -> ":System" : selects the intended role
activate ":System"

":System" --> A : requests data (employeeId, organizationRole, name, address, phoneNumber, email, socCode, DoctorIndexNumber)
deactivate ":System"

A -> ":System" : types requested data
activate ":System"
":System" --> A : shows all data and requests confirmation
deactivate ":System"

A -> ":System" : confirms the data
activate ":System"
":System" --> A : informs operation success
deactivate ":System"

deactivate A

@enduml