@startuml
autonumber
actor Administrator as A

activate A
A -> ":System" : starts registering a new employee
activate ":System"
":System" --> A : asks to select the employee role
deactivate ":System"

A -> ":System" : selects the intended role
activate ":System"
/'ESTOU AQUI!!!!!!!!!!'/
":System" --> A : shows collecting methods list and  ask to select one or more
deactivate ":System"
/'down here it still todo: '/
A -> ":System" : selects collecting methods
activate ":System"
":System" --> A : shows all data and requests confirmation
deactivate ":System"

A -> ":System" : confirms the data
activate ":System"
":System" --> A : informs operation success
deactivate ":System"

deactivate A

@enduml