@startuml
skinparam classAttributeIconSize 0

class RegisterEmployeeUI {
}

class RegisterEmployeeController {
}

class Employee {
- role
- employeeID
- name
- address
- phoneNumber
- e-Mail
- socCode
+Employee(role, employeeID, name, address, phoneNumber, email, socCode)
+getEmployeeId()
+getName()
+getAddress()
+getPhoneNumber()
+getEmail()
+getSocCode()
+getRole()
+toString()
+equals(otherObject)
+generateEmployeeID(name)
+checkNameRules()
+checkAddressRules()
+checkPhoneNumberRules()
+checkEmailRules()
+checkSocCodeRules()


}

class SpecialistDoctor {
- doctorIndexNumber
}

class OrgRole {
- description
}

class OrgRoleDto {
- description
+ getDescription()
}

class EmployeeDto {
- roleDesignation
- employeeID
- name
- address
- phoneNumber
- e-Mail
- socCode
+getName()
+getAddress()
+getPhoneNumber()
+getEmail()
+getSocCode()
+getRoleDesignation()
+Employee(roleDesignation, employeeID, name, address, phoneNumber, e-Mail, socCode)
+getEmployeeId()
+getName()
+getAddress()
+getPhoneNumber()
+getEmail()
+getSocCode()
}

class SpecialistDoctorDto {
}

class User {
}

RegisterEmployeeUI ..> RegisterEmployeeController
Employee <|-- SpecialistDoctor
RegisterEmployeeController ..> Employee
RegisterEmployeeController ..> SpecialistDoctor
RegisterEmployeeUI ..> EmployeeDto
RegisterEmployeeUI ..> SpecialistDoctorDto
RegisterEmployeeController ..> EmployeeDto
RegisterEmployeeController ..> SpecialistDoctorDto
RegisterEmployeeController ..> OrgRoleDto
RegisterEmployeeUI ..> OrgRoleDto
RegisterEmployeeController ..> Company
RegisterEmployeeController ..> OrgRole

EmployeeDto <|-- SpecialistDoctorDto

Employee "*" -- "1" OrgRole : has/plays >
Company "1" -- "*" OrgRole : comprehends >
Company "*" -- "1" Employee : employ >
Employee "0..1" -- "1" User : relates to >

RegisterEmployeeController ..> User


@enduml