@startuml
hide empty methods
hide empty attributes
left to right direction
skinparam classAttributeIconSize 0

class Company {
    -String designation
    -TestStore testStore
    -ClientStore clientStore
    +getTestStore()
    +getClientStore()
}

class TestStore {
    +getTestsInfo
}

class ClientStore {
    +getClientInfo()
}

class CompanyPerformanceAnalysisController{
    -Company company
    +getTestOverview()
    +findWorstSubIntWithBenchmarkAlgorithm(firstDayToAnalyse, lastDayToAnalyse)
    +findWorstSubIntWithBruteforceAlgorithm(firstDayToAnalyse, lastDayToAnalyse)
}

class CompanyPerformanceAnalysisUI{
}

CompanyPerformanceAnalysisUI ..> CompanyPerformanceAnalysisController
CompanyPerformanceAnalysisController ..> Company
CompanyPerformanceAnalysisController ..> ClientStore
CompanyPerformanceAnalysisController ..> TestStore

@enduml