@startuml
autonumber
actor "Laboratory Coordinator" as LC

participant ":CompanyPerformanceAnalysisUI" as UI
participant ":CompanyPerformanceAnalysisController" as CTRL
participant ":Company" as CMP
participant ":CompanyPerformanceAnalysis" as CPA
participant ":Test" as TST

activate LC
LC -> UI : asks to see an overview of all the tests performed and analyse the overall performance of the company
activate UI

UI -> CTRL : testOverview = getTestOverview()
activate CTRL

CTRL -> CMP : get

'array of int with:
'number of clients
'number of tests waiting for results
'number of tests waiting for diagnosis
'total number of tests processed in the laboratory in each day
'...week
'...month
'...year

UI --> LC : shows an overview of all the tests performed, asks the interval of time to be analysed and asks the algorithm to use
deactivate UI



LC -> UI : types requested data (e.g firstDayToAnalyse, lastDayToAnalyse, chosenAlgorithm)
activate UI

UI --> LC : shows the overall performance of the company for the chosen interval of time
deactivate UI


@enduml