@startuml
'skinparam linetype ortho
hide empty methods
hide empty attributes
'left to right direction
skinparam classAttributeIconSize 0

class Company {
    -String designation
    -TestStore testStore
    -ClientStore clientStore
    +getTestStore()
    +getClientStore()
}

class TestStore {
    +getNumTestsWaitingForResultsDayOrInterval(beginningDay, endingDay)
    +getNumTestsWaitingForDiagnosisDayOrInterval(beginningDay, endingDay)
    +getNumTestsProcessedInLabDayOrInterval(beginningDay, endingDay)
    +getNumberOfTestsByIntervalDateOfTestRegistration(beginningDay, endingDay)
    +getNumberOfTestsByIntervalDateOfDiagnosis(beginningDay, endingDay)
}

class ClientStore {
    +getClients()
}

class CompanyPerformanceAnalysisController{
    -Company company
    +getNumClients()
    +getTestInfoDayOrInterval(beginningDay, endingDay)
    +makeIntervalArray(beginningDay, endingDay)
    +findWorstSubIntWithChosenAlgorithm(beginningDay, endingDay, chosenAlgorithm)
    +getChosenAlgorithmAdapter(chosenAlgorithm)
}

class CompanyPerformanceAnalysisUI{
}

interface SubMaxSumAlgorithms <<interface>> {
    +findSubMaxSum(interval)
}

class BenchmarkAlgorithmAdapter{
    +findSubMaxSum(interval)
}

class BruteForceAlgorithmAdapter{
    +findSubMaxSum(interval)
}

class Sum{
    +Max(seq)
}

class BruteForceAlgorithm{
    +Max(seq)
}

CompanyPerformanceAnalysisUI ..> CompanyPerformanceAnalysisController
CompanyPerformanceAnalysisController ..> Company
CompanyPerformanceAnalysisController ..> ClientStore
CompanyPerformanceAnalysisController ..> TestStore
CompanyPerformanceAnalysisController "1" --> "1" SubMaxSumAlgorithms : makes use of
BenchmarkAlgorithmAdapter --> Sum
BruteForceAlgorithmAdapter --> BruteForceAlgorithm

class BenchmarkAlgorithmAdapter implements SubMaxSumAlgorithms
class BruteForceAlgorithmAdapter implements SubMaxSumAlgorithms

@enduml