@startuml

skinparam classAttributeIconSize 0
hide empty methods
hide empty attributes
left to right direction

class Company{
- designation
}

class Test{
- NhsCode
- code
- dateOfTestRegistration
}

class Client{
- clientsCitizenCardNumber
- nhsNumber
- birthDate
- sex
- tinNumber
- email
- name
- phoneNumber
}

class LaboratoryCoordinator{
}

class CompanyPerformance{
- beginningDate
- endingDate
- chosenAlg
- clientsNum
- processTestsNum
- testInfoDay
- testInfoWeek
- testInfoMonth
- testInfoYear
- worstSubInt
}

Company "1" -- "*" Test : conducts >
LaboratoryCoordinator "1..*" -- "*" Test : analyses >
LaboratoryCoordinator "1..*" -- "*" Client : analyses >
Company "1" -- "*" CompanyPerformance : has >

@enduml