@startuml

autonumber
actor "Receptionist" as MLT

activate MLT
MLT -> ":System" : asks to register a test to be performed to a registered client
activate ":System"
":System" --> MLT :requests data (CitizenCardNumber, NHScode) \n and shows test types to select one
deactivate ":System"

MLT -> ":System" : sypes requested data and selects test type
activate ":System"

":System" --> MLT : shows category(ies) associated with test type request to select one
deactivate ":System"
MLT -> ":System" : selects category
activate ":System"

loop while user adds parameters
":System" --> MLT : shows all parameters associated selected category
deactivate ":System"
MLT -> ":System" : selects parameter
activate ":System"
end
":System" --> MLT : shows Test data and requests confirmation
deactivate ":System"
MLT -> ":System" : confirms the data
activate ":System"
":System" --> MLT : informs operation success
deactivate ":System"
deactivate MLT

@enduml