@startuml
hide empty methods
hide empty attributes
left to right direction
skinparam classAttributeIconSize 0

package Core {

package Domain {

package Model {

class Company {
    -String designation
    -TestStore testStore
    +getTestStore()
    +createReport(reportText)
}

class Report {
    - int REPORTTEXT_MAX_LENGTH
    - String reportText
    - Report report
    + Report(reportText)
    + checkReportTextRules(reportText)
    + countWords(reportText)
    + equals(reportObject)
    + create(reportText)
}

class Test {
    -String NHSCode
    -String code
    +getCode()
}

class TestParameter {
    +getParametersResults(listTestParams)
}

}

package Stores {

class TestStore {
    -list<Test> testsReadyToDiagnose
    +getTestsReadyToDiagnose()
    +getTestByCode(code)
    +getTestParameters(tst)
    +addReportToTest(selectedTest)
}

}

}

package Mappers {

class TestMapper {
    +toDTO(listTestsToDiagnose)
    +toDTO(obj)
}

}

package DTO {

class TestsDTO {
    -String NHSCode
    -String code
    +create(NHSCode, code)
    +getCode()
}

}

package Controllers {

class WriteReportController {
    -Company company
    -Report report
    +getTeststoDiagnose()
    +getTestParametersResults(code)
    +createReport(reportText)
    +addReportToTest(code)
}

}

}

package UI {

package Console {

class WriteReportUI {
}

}

}

WriteReportUI ..> WriteReportController
WriteReportUI ..> TestDTO
WriteReportController ..> TestMapper
WriteReportController ..> Company
WriteReportController ..> TestStore
WriteReportController ..> TestDTO
TestStore "1" -> "*" Test : adopts >
Company "1" --> "*" Report : knows >
Report "1" --> "1" Test : is of >
TestMapper ..> Test
TestMapper ..> TestDTO

@enduml