@startuml
autonumber
actor Administrator as A

activate A
A -> ":System" : asks to specify a new test type
activate ":System"
":System" --> A : requests data (code, description, collectingMethod)
deactivate ":System"
A -> ":System" : types requested data
activate ":System"
":System" --> A : shows available categories and request to select one or more
deactivate ":System"
A -> ":System" : selects requested data
activate ":System"
":System" --> A : show test type data and requests confirmation
deactivate ":System"
A -> ":System" : confirms the data
activate ":System"
":System" --> A : informs operation success
deactivate ":System"

deactivate A

@enduml