@startuml

skinparam classAttributeIconSize 0
hide empty methods
hide empty attributes
left to right direction

class Company{
- designation
}
class Parameter{
- designation
}
class TestType{
- designation
}
class Test{
- code
- NhsCode
- createdAt

}
class collectingMethod{
 - name
 - description
 }

 TestType -[hidden]right-|> Company

Test "*" -- "1" TestType : classified as >
Test "*" -- "1..*" Parameter : requested analysis of >
Company "1" -- "*" TestType : conducts >
Company "1" -- "*" Parameter : capable of analysing >
Company "1" -- "*" Administrator : know >
TestType "*" -- "1..*" Parameter : characterized by >
TestType "1" -- "1..*" collectingMethod : has a >
TestType "*" -- "1" Administrator : created by >

@enduml