@startuml
autonumber
actor Administrator as A

activate A
A -> ":System" : asks to specify a new test type
activate ":System"
":System" --> A : requests data (TestType name)
deactivate ":System"
A -> ":System" : types requested data
activate ":System"
":System" --> A : request how many collecting methods to be added
deactivate ":System"
A -> ":System" : types requested data
activate ":System"

loop for each collecting method to be added
":System" --> A : Request for collecting method data(name, description)
deactivate ":System"
A -> ":System" : types requested data
activate ":System"
/'":System" --> A : show collecting method data and request confirmation
deactivate ":System"
A -> ":System" : confirms data
activate ":System"'/
end

":System" --> A : show complete test type data and requests confirmation
deactivate ":System"
A -> ":System" : confirms the data
activate ":System"
":System" --> A : informs operation success
deactivate ":System"

deactivate A

@enduml