@startuml
title SD_getTestsWithNoSamples(selectedCal)

autonumber

participant "testStore\n:TestStore" as TEST_STORE
participant "calTestList\n:List<Test>" as LIST
participant "listTestsNoSamples\n:List<Test>" as LIST_NO_SAMPLES
participant "test\n :Test" as TEST_OBJ
participant "selectedCal\n:ClinicalAnalysisLaboratory" as CAL

[o-> TEST_STORE : getTestsWithNoSamples(selectedCal)
activate TEST_STORE

TEST_STORE --> LIST_NO_SAMPLES** : create()

TEST_STORE -> CAL : calTestList = getCalTestList()
activate CAL
deactivate CAL

loop for each object in calTestList
TEST_STORE -> LIST : test = get(i)
activate LIST
deactivate LIST

TEST_STORE -> TEST_OBJ : boolean = hasSamples()
activate TEST_OBJ
deactivate TEST_OBJ

opt boolean = true


TEST_STORE -> LIST_NO_SAMPLES : add(test)
activate LIST_NO_SAMPLES
deactivate LIST_NO_SAMPLES

end
end


[<-- TEST_STORE : listTestsNoSamples
deactivate TEST_STORE



@enduml
