@startuml
autonumber
'hide footbox
actor "Receptionist" as RC

participant ":RegisterClientUI" as UI
participant ":RegisterClientController" as CTRL
participant ":Company" as CP
participant "session\n:UserSession" as SESSAO
participant "cl: Client" as CL


activate RC
RC -> UI : asks to register a new client
activate UI
UI --> RC : requests data (clients citizen card number, NHS number,  birth \n date, sex, TIN number, e-mail, name, phone number)
deactivate UI

RC -> UI : types requested data
activate UI

UI -> CTRL : createClient(clients citizen card number, NHS number,  birth \n date, sex, TIN number, e-mail, name, phone number)
activate CTRL

CTRL -> CP : cl = createClient(clients citizen card number, NHS number,  birth \n date, sex, TIN number, e-mail, name, phone number)
activate CP
CP -->  CL** : create(clients citizen card number, NHS number,  birth \n date, sex, TIN number, e-mail, name, phone number)
deactivate CP

CTRL -> CP : validateClient(cl)
activate CP

deactivate CP
deactivate CTRL

UI --> RC : informs operation sucess
deactivate CP
deactivate UI

RC -> UI : confirms the data
activate UI

UI -> CTRL : saveClient()
activate CTRL

CTRL -> CP : saveClient(cl)
activate CP
CP -> CP : validateClient(cl)
activate CP
deactivate CP
CP -> CP : addClient(cl)
activate CP
deactivate CP
|||
deactivate CP

CTRL -> SESSAO : addUser(String name, String email, String pwd)
activate SESSAO
SESSAO -> SESSAO : existsUser(String email)
activate SESSAO
deactivate SESSAO
deactivate SESSAO










UI --> RC: informs operation success

deactivate CP
deactivate CTRL
deactivate UI



deactivate CTRL
deactivate UI

deactivate RC

@enduml