@startuml
skinparam classAttributeIconSize 0

class Client {
-clientsCitizenCardNumber
-nhsNumber
-birthDate
-sex
-tinNumber
-email
-name
-phoneNumber
+Client(clientsCitizenCardNumber, nhsNumber, birthDate \n, sex, tinNumber, email, name, phoneNumber )
}

class UserSession{
+addUser(String name, String email, String pwd)
+existsUser(String email)
}



class Company {
-designation
}





class CreateTaskController {
  +createClient(clientsCitizenCardNumber, nhsNumber, birthDate \n, sex, tinNumber, email, name, phoneNumber)
  +saveClient()
}

class CreateTaskUI {

}

CreateTaskUI ..> CreateTaskController
CreateTaskController ..> Company
CreateTaskController ..> Client
CreateTaskController ..> UserSession
'/Client ..> UserSession'/
Company "1" --> "*" Client : knows


@enduml